version: '3'
services:
  sch:
    container_name: sch
    image: ktkdaskrishna/sch:latest
    depends_on:
      - postgres
    networks:
      - db_nw
      - web_nw
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      - DEFAULT_EMAIL=admin@example.com
      - DEFAULT_PASSWORD=admin
      - RESET_DB=no
      - DOC_LINK=https://github.com/ktkdaskrishna/ISO
      - VERSION=3.5.3
      - APP_NAME=Securado Compliance Hub
      - POSTGRES_USER=db1
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=db1
      - POSTGRES_DB=db1
      - GUNICORN_WORKERS=2
  sch-worker:
    container_name: sch-worker
    image: yourusername/sch:latest
    depends_on:
      - postgres
    networks:
      - db_nw
      - web_nw
    restart: unless-stopped
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      - VERSION=3.5.3
      - APP_NAME=Securado Compliance Hub
      - AS_WORKER=yes
      - POSTGRES_USER=db1
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=db1
      - POSTGRES_DB=db1
      - WORKER_CONCURRENCY=1
      - WORKER_LOG_LEVEL=DEBUG
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: db1
      POSTGRES_PASSWORD: db1
      POSTGRES_DB: db1
      PGDATA: /data/postgres
    networks:
      - db_nw
    restart: unless-stopped

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
volumes:
  dbdata:
